<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	
    <title><?php echo $title ?></title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $base_url;?>css/bootstrap.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="<?php echo $base_url;?>css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="<?php echo $base_url;?>css/plugins/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo $base_url;?>css/sb-admin-2.css" rel="stylesheet">

	<!-- DataTables CSS -->
    <link href="<?php echo $base_url;?>css/plugins/dataTables.bootstrap.css" rel="stylesheet">


    <!-- Morris Charts CSS -->
    <link href="<?php echo $base_url;?>css/plugins/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $base_url;?>font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo $base_url;?>css/plugins/chart/css/graph.css" rel="stylesheet">
	<link href="<?php echo $base_url;?>css/slide.css" rel="stylesheet">
	<link rel="stylesheet" href="<?php echo $base_url;?>libs/chosen.css">
	  <style type="text/css" media="all">
		/* fix rtl for demo */
		.chosen-rtl .chosen-drop { left: -9000px; }
	  </style>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	<script src="<?php echo $base_url;?>js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $base_url;?>js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="<?php echo $base_url;?>js/plugins/metisMenu/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="<?php echo $base_url;?>js/plugins/morris/raphael.min.js"></script>
    <script src="<?php echo $base_url;?>js/plugins/morris/morris.min.js"></script>
    <script src="<?php echo $base_url;?>js/plugins/morris/morris-data.js"></script>
	

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
				<span><i class="fa fa-phone-square"></i></span>
				SISTEM PAKAR CBR </a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <!--<li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>-->
                        <li><a href="<?php echo site('user/logout');?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                          <?php  /* <img src="<?php echo site('Layout/images/telkom.png');?>"/>
                         */ ?>
						 <i class="fa fa-forumbee"></i>
						 </li>
						<?php $parameter = Core::request();?>
                        <li>
                            <a class="active" href="<?php echo site('admin/')?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <?php /** 
						<li>
                            <a class="<?php echo ($parameter['controller'] =='lecturer')? 'active' : ''; ?>" href="<?php echo site('lecturer/index')?>"><i class="fa fa-user-md"></i> <?php echo __('Lecturers');?></a>
                        </li>
						<li>
                            <a class="<?php echo ($parameter['controller'] =='student')? 'active' : ''; ?>" href="<?php echo site('student/index')?>"><i class="fa fa-graduation-cap"></i> <?php echo __('Students');?></a>
                        </li>
						***/ ?>
						<li>
                            <a class="<?php echo ($parameter['controller'] =='user')? 'active' : ''; ?>" href="<?php echo site('user/index')?>"><i class="fa fa-users"></i> <?php echo __('Users');?></a>
                        </li>
						<li>
                            <a class="<?php echo ($parameter['controller'] =='jurnal')? 'active' : ''; ?>" href="<?php echo site('jurnal/index')?>"><i class="fa fa-file"></i> <?php echo __('Jurnals');?></a>
                        </li>
						
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

		<?php /**<div class="row2">
			<div id="bg-header">
			
			</div>
		</div> **/?>

        <div id="page-wrapper">
            <div class="row2">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $header;?></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            
            <?php echo $content;?>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery Version 1.11.0 -->
    
	<!-- DataTables JavaScript -->
    <script src="<?php echo $base_url;?>js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="<?php echo $base_url;?>js/plugins/dataTables/dataTables.bootstrap.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="<?php echo $base_url;?>js/sb-admin-2.js"></script>
	 <script>
    $(document).ready(function() {
        $('#dataTables-example').dataTable();
    });
    </script>
	
	<script>
		var SITE_URL ="<?php echo $site_url; ?>"
	</script>
	
	<script type="text/javascript" src="<?php echo $base_url;?>js/ajax.js"></script>
	<script src="<?php echo $base_url; ?>libs/chosen.jquery.js" type="text/javascript"></script>
  <script src="<?php echo $base_url; ?>libs/docsupport/prism.js" type="text/javascript" charset="utf-8"></script>
  <script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
      $(selector).chosen(config[selector]);
    }
  </script>
	<footer>
		<p>&copy;Copyright.STMIK Denpasar - 2014</p>
	</footer>

</body>

</html>
