<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
                                            <th>NIP</th>
											<th>Photo</th>
                                            <th>Name</th>
                                            <th>Address</th>
											<th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($lecturers as $lecturer):?>
										<tr class="">
											<td><?php echo $i++;?></td>
                                            <td><?php echo $lecturer['nip']?></td>
                                            <td>
											<?php if(file_exists(FILE_PATH.'photo'.DS.$lecturer['photo'])):?>
											<img width="50" src="<?php echo site('Media/photo/'.$lecturer['photo'])?>">
											
											<?php else:?>
											<img width="50" src="<?php echo site('Media/photo/no-photo.png')?>">
											
											<?php endif;?>
											
											</a></td>
                                            <td><?php echo $lecturer['name']?></td>
											<td><?php echo $lecturer['address']?></td>
                                            <td class="center" align="center">
												<a href="<?php echo site('lecturer/edit/'.$lecturer['id_lecturer'])?>">
													<i class="fa fa-pencil-square fa-fw"></i>
												</a>
												<a href="<?php echo site('lecturer/delete/'.$lecturer['id_lecturer'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('lecturer/add')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->