<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Tambah Data Jurnal<br/>
	</div>

<div class="panel-body">
	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form enctype="multipart/form-data" role="form" method="post" action="<?php echo site('jurnal/save')?>">
				<div class="form-group">
					<label>Nama Penulis I</label><br>
					<!--<input class="form-control" name="nim" value="<?php echo (isset($request['nim']))? $request['nim']:'' ?>">					
					-->
					<?php /** <select style="width:350px;"  class="chosen-select" name="nim" data-placeholder="Pilih Mahasiswa">
						<option value="0">Pilih Penulis..</option>
						<?php foreach($student as $key => $value):?>
						<option value="<?php echo $value['nim'];?>"><?php echo $value['name'];?></option>
						<?php endforeach;?>
					</select>
					**/ ?>
					<input class="form-control" name="writer_1" value="<?php echo (isset($request['writer_1']))? $request['writer_1']:'' ?>">					
				
				</div>
				<div class="form-group">
					<label>Nama Penulis II</label><br>
					
					<input class="form-control" name="writer_2" value="<?php echo (isset($request['writer_2']))? $request['writer_2']:'' ?>">					
				
				</div>
				
				<div class="form-group">
					<label>Title</label>
					<input class="form-control" name="title" value="<?php echo (isset($request['title']))? $request['title']:'' ?>">
				</div>
				<div class="form-group">
					<label>Jenis Jurnal</label><br>
					<select style="width:350px;" class="chosen-select" name="jenis" data-placeholder="Select Your Options">
						<option value="0">Pilih Jenis Jurnal</option>
						<?php foreach(OptionJenis() as $k => $v):?>
						<option value="<?php echo $k;?>"><?php echo $v;?></option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label>Keterangan</label>
					<textarea class="form-control" name="abstract" ><?php echo (isset($request['abstract']))? $request['abstract']:'' ?></textarea>
				</div>
				<div class="form-group">
					<label>Year</label><br>
					<!--<input class="form-control" name="year" value="<?php echo (isset($request['year']))? $request['year']:'' ?>">
					-->
					<select style="width:120px;"  class="chosen-select" name="year" data-placeholder="Pilih Mahasiswa">
						<option value="2015">Pilih Tahun..</option>
						<?php for($ii=1998;$ii<=2015;$ii++):?>
						<option value="<?php echo $ii;?>"><?php echo $ii;?></option>
						<?php endfor;?>
					</select>
				
				</div>
				<?php /** <div class="form-group">
					<label>Pembimbing</label><br>
					<select style="width:350px;" multiple class="chosen-select" name="lecturer_ids[]" data-placeholder="Select Your Options">
						<option value="0">Pilih Dosen Pembimbing..</option>
						<?php foreach($lecturer as $key => $value):?>
						<option value="<?php echo $value['id_lecturer'];?>"><?php echo $value['name'];?></option>
						<?php endforeach;?>
					</select>
				</div>
				**/?>
				<div class="form-group">
					<label>File (docx)</label>
					<input type="file" name="file" value="<?php echo (isset($request['file']))? $request['file']:'' ?>">
					
				</div>
				<div class="form-group">
					<label>File Lengkap (docx)</label>
					<input type="file" name="full_file" value="<?php echo (isset($request['full_file']))? $request['full_file']:'' ?>">
					
				</div>
				<button class="btn btn-primary" type="submit">Save</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>