<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Student<br/>
	</div>

<div class="panel-body">
	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form enctype="multipart/form-data" role="form" method="post" action="<?php echo site('jurnal/save')?>">
				<div class="form-group">
					<label>NIM</label>
					<input class="form-control" name="nim" value="<?php echo (isset($request['nim']))? $request['nim']:'' ?>">					
				</div>
				
				<div class="form-group">
					<label>Title</label>
					<input class="form-control" name="title" value="<?php echo (isset($request['title']))? $request['title']:'' ?>">
				</div>
				<div class="form-group">
					<label>Abstract</label>
					<textarea class="form-control" name="abstract" ><?php echo (isset($request['abstract']))? $request['abstract']:'' ?></textarea>
				</div>
				<div class="form-group">
					<label>Year</label>
					<input class="form-control" name="year" value="<?php echo (isset($request['year']))? $request['year']:'' ?>">
				</div>
				<div class="form-group">
					<label>Pembimbing</label>
					<select style="width:350px;" multiple class="chosen-select" name="lecturer_ids[]" data-placeholder="Select Your Options">
						<option value="0">Pilih Dosen Pembimbing..</option>
						<?php foreach($lecturer as $key => $value):?>
						<option value="<?php echo $value['id_lecturer'];?>"><?php echo $value['name'];?></option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label>File (docx)</label>
					<input type="file" name="file" value="<?php echo (isset($request['file']))? $request['file']:'' ?>">
					
				</div>
				<button class="btn btn-primary" type="submit">Save</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>