<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Ubah Data Jurnal<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form enctype="multipart/form-data" role="form" method="post" action="<?php echo site('jurnal/save/'.$request['id_jurnal'])?>">
				<div class="form-group">
					<label>Nama Penulis I</label>
					<input  class="form-control" name="writer_1" value="<?php echo (isset($request['writer_1']))? $request['writer_1']:'' ?>">					
				</div>
				<div class="form-group">
					<label>Nama Penulis II</label>
					<input  class="form-control" name="writer_2" value="<?php echo (isset($request['writer_2']))? $request['writer_2']:'' ?>">					
				</div>
				
				<div class="form-group">
					<label>Title</label>
					<input class="form-control" name="title" value="<?php echo (isset($request['title']))? $request['title']:'' ?>">
				</div>
				<div class="form-group">
					<label>Jenis Jurnal</label><br>
					<select style="width:350px;" class="chosen-select" name="jenis" data-placeholder="Select Your Options">
						<option value="0">Pilih Jenis Jurnal</option>
						<?php foreach(OptionJenis() as $k => $v):?>
						<option <?php if($k == $request['jenis']) echo 'SELECTED'; ?> value="<?php echo $k;?>"><?php echo $v;?></option>
						<?php endforeach;?>
					</select>
				</div>
				
				<div class="form-group">
					<label>Keterangan</label>
					<textarea class="form-control" name="abstract" ><?php echo (isset($request['text']))? $request['text']:'' ?></textarea>
				</div>
				<div class="form-group">
					<label>Year</label>
					<input class="form-control" name="year" value="<?php echo (isset($request['year']))? $request['year']:'' ?>">
				</div>
				
				
				<div class="form-group">
					<label>File (docx)</label>
					<input type="file" name="file" value="<?php echo (isset($request['file']))? $request['file']:'' ?>">
					
				</div>
				<div class="form-group">
					<label>File Lengkap (docx)</label>
					<input type="file" name="full_file" value="<?php echo (isset($request['full_file']))? $request['full_file']:'' ?>">
					
				</div>
				<button class="btn btn-primary" type="submit">Save</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>