<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th width="40">No.</th>
                                            <th width="100">Jenis</th>
											<th width="200">Penulis I</th>
											<th width="200">Penulis II</th>
											<th>Title</th>
											<th>Year</th>
                                            <th width="120">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($jurnals as $jurnal):?>
										<tr class="">
											<?php $pemb = $Model->IN(explode(",",$jurnal['lecturer_ids'])); ?>
											
											<td><?php echo $i++;?></td>
                                            <td><?php echo $jurnal['jenis']?></td>
                                            <td>
											<?php /**if(!empty($pemb)):
													foreach($pemb as $perm): ?>
													<?php echo $perm['name'] .'<br>';?>
											<?php  
													endforeach;
													endif; **/ ?>
											<?php echo $jurnal['writer_1']?>
											</td>
											<td>
											<?php echo $jurnal['writer_2']?>
											</td>
											<?php //$lecturer = $this->loadmodel('LecturerModel'); ?>

											<td><?php echo $jurnal['title']?></td>
                                            <td><?php echo $jurnal['year']?></td>
											<!--<td><?php echo $jurnal['filepath']?></td>
                                            -->
											<td class="center" align="center">
												<a href="<?php echo site('jurnal/edit/'.$jurnal['id_jurnal'])?>">
													<span class="btn btn-success"><i class="fa fa-pencil-square fa-fw"></i></span>
												</a>
												<a href="<?php echo site('jurnal/delete/'.$jurnal['id_jurnal'])?>">
													<span class="btn btn-danger"><i class="fa fa-times-circle fa-fw"></i></span>
												</a>
											</td>
											<?php $pemb = array(); endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('jurnal/add')?>"><?php echo lang('Add New');?></a>
                                <a class="btn btn-warning btn-lg" type="button" href="<?php echo site('problem/deleteall')?>">Bersihkan Riwayat</a>
                            </p>
							<p><span style="font-size:11px;color:#ff0000;">* Untuk pencarian yang maksimal silakan bersihkan history setiap melakukan perubahan data jurnal.</span></p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->