<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th>No.</th>
                                            <th>NIM</th>
											<th>Pembimbing</th>
											<th>Title</th>
                                            <th>Year</th>
                                            <th>filepath</th>
											<th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($jurnals as $jurnal):?>
										<tr class="">
											<?php $pemb = $Model->IN(explode(",",$jurnal['lecturer_ids'])); ?>
											
											<td><?php echo $i++;?></td>
                                            <td><?php echo $jurnal['nim']?></td>
                                            <td>
											<?php if(!empty($pemb)):
													foreach($pemb as $perm): ?>
													<?php echo $perm['name'] .'<br>';?>
											<?php  
													endforeach;
													endif;?>
											</td>
											<?php //$lecturer = $this->loadmodel('LecturerModel'); ?>

											<td><?php echo $jurnal['title']?></td>
                                            <td><?php echo $jurnal['year']?></td>
											<td><?php echo $jurnal['filepath']?></td>
                                            <td class="center" align="center">
												<a href="<?php echo site('jurnal/edit/'.$jurnal['id_jurnal'])?>">
													<i class="fa fa-pencil-square fa-fw"></i>
												</a>
												<a href="<?php echo site('jurnal/delete/'.$jurnal['id_jurnal'])?>">
													<i class="fa fa-times-circle fa-fw"></i>
												</a>
											</td>
											<?php $pemb = array(); endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('jurnal/add')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->