<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th width="40">No.</th>
                                            <th width="200">Term</th>
											<th>Tahun</th>
											<th>Jenis</th>
											<th>Pembimbing</th>
											<th>Jumlah</th>
											<th>Tanggal</th>
                                            <th width="60">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($problems as $problem):?>
										<tr class="">
											<?php $pemb = $Model->IN($problem['lecturer_ids']); ?>
											
											<td><?php echo $i++;?></td>
                                            <td><?php echo $problem['term'] ?></td>
											<td><?php echo $problem['tahun'] ?></td>
											<td><?php echo (!$problem['jenis'])? '-': $problem['jenis'] ?></td>
                                            <td>
											<?php if(!empty($pemb)):
													foreach($pemb as $perm): ?>
													<?php echo $perm['name'] .'<br>';?>
											<?php  
													endforeach;
													else:
													echo '-';
													endif;?>
											</td>
											<?php //$lecturer = $this->loadmodel('LecturerModel'); ?>
											<td><?php echo $problem['count']?></td>
                                            <td><?php echo $problem['created']?></td>
											
											<td class="center" align="center">
												
												<a href="<?php echo site('problem/delete/'.$problem['id_problem'])?>">
													<span class="btn btn-danger"><i class="fa fa-times-circle fa-fw"></i></span>
												</a>
											</td>
											<?php $pemb = array(); endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						<div class="panel-body">
                            <p>
                                <a class="btn btn-warning btn" type="button" href="<?php echo site('problem/deleteall')?>">Bersihkan Riwayat</a>
                                
                            </p>
                        </div>
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->