<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pencarian Topik Jurnal</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $base_url;?>css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo $base_url;?>css/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $base_url;?>font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	<link href="<?php echo $base_url;?>css/animate.css" rel="stylesheet">
	<link rel="stylesheet" href="<?php echo $base_url;?>libs/chosen.css">
  <style type="text/css" media="all">
	/* fix rtl for demo */
	.chosen-rtl .chosen-drop { left: -9000px; }
  </style>
	<style>
body{
	font-weight:normal;
	color:#000;
}
ol {
    display: block;
    list-style: none;
    -webkit-margin-before: 1em;
    -webkit-margin-after: 1em;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
    -webkit-padding-start: 40px;
    padding: 0;
    margin-left: 0px;
}
a:hover{text-decoration:none;}

#search {
    float: right;
    margin-top: 9px;

}

.search {
    padding: 5px 0;
    height: 30px;
    position: relative;
    left: ;
    float: left;
    line-height: 22px;
	width:100%;
}

.search input {
	float: Left;
	width:100%;
	-webkit-transition: all 0.7s ease-in-out;
	-moz-transition: all 0.7s ease-in-out;
	-o-transition: all 0.7s ease-in-out;
	transition: all 0.7s ease-in-out;
	height: 30px;
	line-height: 18px;
	padding: 0 10px;
	border-radius:1px;
}

.search:hover input, .search input:focus {
	margin-left: 0px;
}

.btn {
    height: 30px;
    position: absolute;
    right: 0;
    top: 5px;
    border-radius:1px;
}
.judul-stmik{
	display:none;
}
@media (max-width: 768px){
	.logo-stmik {
		position: relative;
		left: 0;
	}
	.logo-stmik img {
		height: 75px;
		display: inline-block;
		text-align: left;
		float: left;
	}
	.judul-stmik{
		display:block;
	}
	.judul-stmik {
		float: left;
		margin-left: 15px;
	}
	.logo-stmik {
		display: block;
		border-bottom: 1px solid;
		height: auto;
		overflow: hidden;
	}
}
.clear {
	clear:both;
}
.toolkit {
    margin-top: 30px;
    padding-top: 15px;
    left: -25px;
    position: relative;
}
.toolkit span.tools {
    padding: 20px 0;
}
i.fa.fa-cog {
    font-size: 20px;
}
.aTools {
    cursor: pointer;
    padding: 5px;
}
.border-bottom {
    border-bottom: 1px solid #E4E2E2;
    min-height: 30px;
    padding-top: 15px;
    padding-bottom: 10px;
}
.tool-option {
    margin-top: 10px;
	text-align: left;
}
.modal-body ol.breadcrumb {
		display: none;
	}
.btn[type="submit"]{
	height:45px;
	top:0px;
}
.no-radius {
	border-radius:0px;
}
.form-group {
    margin-bottom: 5px;
}
.penulis {
    height: 35px;
    padding: 5px;
}
</style>
    <!-- jQuery -->
    <script src="<?php echo $base_url;?>js/jquery.js"></script>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="<?php echo site('');?>#" class="navbar-brand topnav animated slideInDown">
					Pencarian jurnal di STMIK Denpasar
				</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse animated bounce" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">Beranda</a>
                    </li>
                    <li>
                        <a href="#services">Tentang</a>
                    </li>
                    <!--<li>
                        <a href="#contact">Bantuan</a>
                    </li>-->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

	<div class="ajax-result animated rotateInUpLeft"></div>
    <!-- Header -->
	<div class="home-data animated flipInX">
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <img class="animated flipInX" src="<?php echo site('Layout/frontend/img/logo-big.png');?>">
                        
						<?php echo ($content);?>
                       <!-- <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li>
                                <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li>
                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                            </li>
                        </ul>
						-->
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Menggunakan metode CBR ( Case-Base)</h2>
                    <p class="lead">
						Dengan metode ini pencarian dengan kata kunci yang pernah digunakan akan lebih cepat ditemukan karena terdapat 4 langkah dalam metode ini. 
					</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="<?php echo site('Layout/frontend/img/DSC_0095-555x200.jpg');?>" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Mempermudah Pencarian</h2>
                    <p class="lead">
					Dengan menggunakan pencarian ini akan mempermudah dalam menemukan jurnal yang sesuai dengan kata kunci pencarian.
					</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="<?php echo site('Layout/frontend/img/1a-555x200.jpg');?>" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                       <!-- <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>-->
                        <!-- <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>-->
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->
	</div>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    
                    <p class="copyright text-muted small">Copyright &copy; STMIK Denpasar 2015. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $base_url;?>js/bootstrap.min.js"></script>
	<!-- Morris Charts JavaScript -->
	<script src="<?php echo $base_url; ?>libs/chosen.jquery.js" type="text/javascript"></script>
  <script src="<?php echo $base_url; ?>libs/docsupport/prism.js" type="text/javascript" charset="utf-8"></script>
  <script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
      $(selector).chosen(config[selector]);
    }
  </script>
	<script>
		$(document).ready(function() {
						
			$('.navbar-right a').click(function(){
				$('.home-data').show();
				$('.ajax-result').hide(500);
			});
			
			$('form#formSearch').keyup(function(){
				var values = $(this).serialize();
				//var q = $('input-lg').val();
				
			/* $.ajax({
				url: "http://localhost/new-cbr/search/ajax",
				type: "post",
				data: values ,
				success: function (response) {
				   $('.ajax-result').html(response);
					$('footer').hide();
					$('.home-data').hide();
					$('.ajax-result').show(500);
				},
				error: function(jqXHR, textStatus, errorThrown) {
				   console.log(textStatus, errorThrown);
				}

 */
			});
				
			});

	</script>
</body>

</html>
