<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Pencarian Jurnal dengan metode CBR</title>

    <!-- Bootstrap -->
    <link href="<?php echo $base_url;?>css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>css/default.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>css/component.css" />
	<link href="<?php echo $base_url;?>css/customize.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	<header class="clearfix">
		<div class="sw_tb">
			<ul>
				<li>
					<a href="#"><?php echo __('login')?></a>
				</li>
			</ul>
		</div>
	</header>
	<div class="container">
	
			<div class="main">
				<ul id="cbp-bislideshow" class="cbp-bislideshow">
					<li><img src="<?php echo $base_url;?>images/1.jpg" alt="image01"/></li>
					<li><img src="<?php echo $base_url;?>images/2.jpg" alt="image02"/></li>
					<li><img src="<?php echo $base_url;?>images/3.jpg" alt="image03"/></li>
					<li><img src="<?php echo $base_url;?>images/4.jpg" alt="image04"/></li>
					<li><img src="<?php echo $base_url;?>images/5.jpg" alt="image05"/></li>
					<li><img src="<?php echo $base_url;?>images/6.jpg" alt="image06"/></li>
				</ul>
				<!--<div id="cbp-bicontrols" class="cbp-bicontrols">
					<span class="cbp-biprev"></span>
					<span class="cbp-bipause"></span>
					<span class="cbp-binext"></span>
				</div>-->
			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<!-- imagesLoaded jQuery plugin by @desandro : https://github.com/desandro/imagesloaded -->
		<script src="<?php echo $base_url;?>js/jquery.imagesloaded.min.js"></script>
		<script src="<?php echo $base_url;?>js/cbpBGSlideshow.js"></script>
		<script>
			$(function() {
				cbpBGSlideshow.init();
			});
		</script>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo $base_url;?>js/bootstrap.min.js"></script>
	<script src="<?php echo $base_url;?>js/modernizr.custom.js"></script>
	<div class="container">
		
		<div class="starter-template">
			<?php echo ($content);?>
		</div>
	</div>
	<footer class="clearfix">
		<div class="sw_tb">
			<p>&copy; 2015 STMIK Denpasar</p>
		</div>
	</footer>
  </body>
</html>
