<div class="container">
	<div class="row">
		<?php foreach($jurnals as $jurnal):?>
		<div class="col-md-12">
		
			<div class="col-md-12">
				
				<div class="hentry sevenup">
					<h2 class="entry-title"><?php echo $jurnal['title']?></h2>
					<p>Penulis : <a class="showMe" href="#"><?php echo $jurnal['name']?></a> , diposting tanggal <abbr class="published"><?php echo $jurnal['created']?></abbr></p>
					<div class="entry-content">
						<h4>Abstract</h4>
						<p class="text"><?php echo $jurnal['text']?>	</p>
						
						<p class="keywords">Kata Kunci :  <i>Prestasi Kerja, Stres Kerja</i></p>
					</div>
				</div>
				<div id="articleFullText">
					<h4>Full Text:</h4>
					<a href="<?php echo site('Media/'.$jurnal['filepath'])?>" class="file" target="_parent">DOCX</a>
				</div>
			</div>
			
		</div>
		<?php endforeach;?>
	</div>
	
	<div class="row" id="temphide" style="display:none">
        <div class="col-md-12"> 
		<div class="row">
		
		<div class="col-md-12">
			
			<div style="
						width: 100%;
						padding: 5px;
						margin-bottom: 15px;">
			<img style="width:auto;" src="<?php echo site('Media/photo/student/'.$jurnals[0]['photo'])?>">
			</div>
			<div class="detail-data">
				<p><label>NIM</label><br>
				<span><?php echo $jurnals[0]['nim'];?></span></p>
				<p><label>Alamat</label><br>
				<span><?php echo $jurnals[0]['address'];?>.</span></p>
			
				<p><label>Tanggal lahir</label><br>
				<span><?php echo $jurnals[0]['bod'];?></span></p>
				
				<?php /** <p><label>Jurusan</label><br>
				<span><?php echo $jurnals[0]['jurusan'];?></span></p>
				
				<p><label>Jenjang Pendidikan</label><br>
				<span><?php echo $jurnals[0]['jenjang'];?></span></p>
				**/?>
			</div>
		</div>
		
		</div>
</div>
      </div>
	
</div>

