<div class="container">
	<div class="row">
		<?php foreach($jurnals as $jurnal):?>
		<div class="col-md-6">
		
			<div class="col-md-12">
				
				<div class="hentry sevenup">
					<h4 class="entry-title" style="line-height: 180%;"><?php echo $jurnal['title']?></h4>
					<p>Penulis : <strong><?php echo implode(" & ",array(ucfirst($jurnal['writer_1']),ucfirst($jurnal['writer_2'])))?> </strong><br> Diposting tanggal <abbr class="published"><strong><?php $date = new DateTime($jurnal['created']);echo $date->format('d M Y'); ?></strong></abbr></p>
					<div class="entry-content">
						<h4>Keterangan</h4>
						<p class="text"><?php echo $jurnal['text']?>	</p>
						
						<!--<p class="keywords">Kata Kunci :  <i>Prestasi Kerja, Stres Kerja</i></p>-->
					</div>
				</div>
				<div id="articleFullText">
					<p>Download file lengkap
					<a href="<?php echo site('Media/'.$jurnal['full_file'])?>" class="file" target="_parent">&nbsp;&nbsp;<i style="font-size:22px" class="fa fa-file-word-o"></i></a></p>
				</div>
			</div>
			
		</div>
		<?php endforeach;?>
	</div>
	
	<div class="row" id="temphide" style="display:none">
        <div class="col-md-12"> 
		<div class="row">
		
		<div class="col-md-12">
			
			<div style="
						width: 100%;
						padding: 5px;
						margin-bottom: 15px;">
			<img style="width:auto;" src="<?php echo site('Media/photo/student/'.$jurnals[0]['photo'])?>">
			</div>
			<div class="detail-data">
				<p><label>NIM</label><br>
				<span><?php echo $jurnals[0]['nim'];?></span></p>
				<p><label>Alamat</label><br>
				<span><?php echo $jurnals[0]['address'];?>.</span></p>
			
				<p><label>Tanggal lahir</label><br>
				<span><?php echo $jurnals[0]['bod'];?></span></p>
				
				<?php /** <p><label>Jurusan</label><br>
				<span><?php echo $jurnals[0]['jurusan'];?></span></p>
				
				<p><label>Jenjang Pendidikan</label><br>
				<span><?php echo $jurnals[0]['jenjang'];?></span></p>
				**/?>
			</div>
		</div>
		
		</div>
</div>
      </div>
	
</div>

