<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>Remote file for Bootstrap Modal</title>  
</head>
<body>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                 <h4 class="modal-title">Detail Jurnal</h4>
            </div>			<!-- /modal-header -->
            <div class="modal-body">
           <?php echo ($content);?>
			</div>			<!-- /modal-body -->
            <?php /** <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div> **/?>
<script>
	$(function() {
		$(".showMe").click(function(){
			$('#temphide').toggle();
		});
	});
</script>

			<!-- /modal-footer -->
</body>
</html>