<div class="container">
	<div class="row">
        <div class="col-md-12">
    		<form id="formSearch" role="form" method="post" action="<?php echo site('search');?>">
			
            <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" name="q" class="form-control input-lg" placeholder="Masukkan kata kunci..." />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            </div>
			</form>
        </div>
	</div>
</div>