<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Student<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form enctype="multipart/form-data" role="form" method="post" action="<?php echo site('student/save')?>">
				<div class="form-group">
					<label>NIM</label>
					<input class="form-control" name="nim" value="<?php echo (isset($request['nim']))? $request['nim']:'' ?>">					
				</div>
				
				<div class="form-group">
					<label>Name</label>
					<input class="form-control" name="name" value="<?php echo (isset($request['name']))? $request['name']:'' ?>">
				</div>
				<div class="form-group">
					<label>Alamat</label>
					<input class="form-control" name="address" value="<?php echo (isset($request['address']))? $request['address']:'' ?>">
				</div>
				<div class="form-group">
					<label>Photo</label>
					<input type="file" name="photo" value="<?php echo (isset($request['photo']))? $request['photo']:'' ?>">
				</div>
				<button class="btn btn-primary" type="submit">Save</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>