<div class="col-lg-12">
<?php echo (isset($msg))?$msg:'';?>
<div class="panel panel-default">
	<div class="panel-heading">
		Form Student<br/>
	</div>

<div class="panel-body">

	<!-- /.row -->
	<div class="row">
		<div class="col-lg-6">
			<form enctype="multipart/form-data" role="form" method="post" action="<?php echo site('student/save/'.$request['nim'])?>">
				<div class="form-group">
					<label>NIM</label>
					<input class="form-control" name="nim" value="<?php echo (isset($request['nim']))? $request['nim']:'' ?>">					
				</div>
				
				<div class="form-group">
					<label>Name</label>
					<input class="form-control" name="name" value="<?php echo (isset($request['name']))? $request['name']:'' ?>">
				</div>
				<div class="form-group">
					<label>Alamat</label>
					<textarea rows="5" class="form-control" name="address"><?php echo (isset($request['address']))? $request['address']:'' ?></textarea>
					
				</div>
				<div class="form-group">
					<label>Photo</label>
					<?php if(!empty($request['photo'])):?>
					<div style="border: 1px solid;
								width: 60px;
								padding: 5px;
								margin-bottom: 15px;">
					<img width="50" src="<?php echo site('Media/photo/student/'.$request['photo'])?>">
					</div>
					<?php endif;?>
					<span class="btn btn-warning btn-file">
						Browse<input  type="file" name="photo" value="<?php echo (isset($request['photo']))? $request['photo']:'' ?>">
					</span>
				</div>
				<button class="btn btn-primary" type="submit">Save</button>
				<button class="btn btn-default" type="reset">Reset</button>
			</form>
        </div>			
	</div>
	<!-- /.row -->
</div>
</div>

</div>