<!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
					<?php echo (isset($msg))?$msg:'';?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php echo $title;?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
											<th width="40">No.</th>
                                            <th width="100">NIP</th>
											<th width="40">Photo</th>
                                            <th>Name</th>
                                            <th>Address</th>
											<th width="120">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
										
                                        <?php $i = 1; foreach($students as $student):?>
										<tr class="">
											<td><?php echo $i++;?></td>
                                            <td><?php echo $student['nim']?></td>
                                            <td>
											<?php if(empty($student['photo']) || file_exists(FILE_PATH.'photo'.DS.'student'.DS.$student['photo'])):?>
											<img width="50" src="<?php echo site('Media/photo/student/'.$student['photo'])?>">
											
											<?php else:?>
											<img width="50" src="<?php echo site('Media/photo/no-photo.png')?>">
											
											<?php endif;?>
											
											</td>
                                            <td><?php echo $student['name']?></td>
											<td><?php echo $student['address']?></td>
                                            <td class="center" align="center">
												<a href="<?php echo site('student/edit/'.$student['nim'])?>">
													<span class="btn btn-success"><i class="fa fa-pencil-square fa-fw"></i></span>
												</a>
												<a href="<?php echo site('student/delete/'.$student['nim'])?>">
													<span class="btn btn-danger"><i class="fa fa-times-circle fa-fw"></i></span>
												</a>
											</td>
											<?php endforeach;?>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
						
						<div class="panel-body">
                            <p>
                                <a class="btn btn-primary btn-lg" type="button" href="<?php echo site('student/add')?>"><?php echo lang('Add New');?></a>
                                
                            </p>
                        </div>
						
						
                        <!-- /.panel-body -->
						
						
						
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->